## Tareas Faltantes
## Mateo Ruiz Navarro
## 201418281

## Tarea No.5

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Condiciones de prueba: masas colgando verticalmente sin tensión T2
L, L1, L2, L3  = 4, 4, 4, 4  # Longitudes
W1, W2         = 10, 20      # Pesos

In [3]:
# 1.a (10 puntos)
# 
# Establezca correctamente los valores numéricos de las condiciones
# iniciales de prueba para una  configuración de 2 masas colgando 
# verticalmente con la tensión T2 = 0

# Puede trabajar con 
#    y = [x0,...x8] 
# o con 
#    y=[x1, ... , x9] 
# siguiendo la notación del libro (eq 8.10)

# Las condiciones iniciales se escogen con la configuración del sistema inicial. las tensiones T1 Y T2 serian
# iguales a los pesos. Como la cuerda 2 no esta tensionada, esta completamente horizontal y el ángulo 2 es cero.

x1 = 1
x2 = 0
x3 = 1
x4 = 0
x5 = 1
x6 = 0
x7 = 10
x8 = 0
x9 = 20

# Vector y para la primera iteración
y = [x1,x2,x3,x4,x5,x6,x7,x8,x9]
print(y)

[1, 0, 1, 0, 1, 0, 10, 0, 20]


In [4]:
# 1.b (10 puntos)
# Escriba las nueve funciones f_i(y)

def f_1(y):
    return L1*y[3] + L2*y[4] + L3*y[5]- L

def f_2(y):
    return L1*y[0] + L2*y[1] - L3*y[2]

def f_3(y):
    return y[6]*y[0] - y[7]*y[1] - W1

def f_4(y):
    return y[6]*y[3] - y[7]*y[4]

def f_5(y):
    return y[7]*y[1] + y[8]*y[2]- W2

def f_6(y):
    return y[7]*y[4] - y[8]*y[5]

def f_7(y):
    return y[0]**2 + y[3]**2 - 1

def f_8(y):
    return y[1]**2 + y[4]**2 - 1

def f_9(y):
    return y[2]**2 + y[5]**2 - 1


In [5]:
# 1.c (10 puntos)
# Escriba una función f_vec(y) que retorne la eq. 8.12
def f_vec(y):
    return np.array([ f_1(y),f_2(y),f_3(y),f_4(y),f_5(y),f_6(y),f_7(y),f_8(y),f_9(y)])

In [6]:
# 1.d (10 puntos)
# 
# Verifique que con nuestras condiciones de prueba, 
# (masas colgando verticalmente),
# se cumple f_vec(y) = 0

vec = f_vec(y)
print(vec)

[0 0 0 0 0 0 0 0 0]


In [7]:
# 1.e (10 puntos)
# implemente la función de derivada parcial para derivar f_i(y) 
# respecto a x_j, evaluada en y.

def DerivadaParcial(ind,jd,y):
    
    DeltaY = 1*10**(-6)
    ynew = []
    yold = []
    for i in range(len(y)):
        ynew.append(y[i])
        yold.append(y[i])
    ynew[jd] = ynew[jd]+DeltaY
    
    ## Derivada Parcial DP
    # Escoge le función a derivar, suma el paso solo en componente donde se hace la derivada parcial y hace 
    # la aproximación a la derivada.
    
    if ind == 1:
        DP = (f_1(ynew) - f_1(yold))/DeltaY
        return DP
    if ind == 2:
        DP = (f_2(ynew)-f_2(yold))/DeltaY
        return DP
    if ind == 3:
        DP = (f_3(ynew)-f_3(yold))/DeltaY
        return DP
    if ind == 4:
        DP = (f_4(ynew)-f_4(yold))/DeltaY
        return DP
    if ind == 5:
        DP = (f_5(ynew)-f_5(yold))/DeltaY
        return DP
    if ind == 6:
        DP = (f_6(ynew)-f_6(yold))/DeltaY
        return DP
    if ind == 7:
        DP = (f_7(ynew)-f_7(yold))/DeltaY
        return DP
    if ind == 8:
        DP = (f_8(ynew)-f_8(yold))/DeltaY
        return DP
    if ind == 9:
        DP = (f_9(ynew)-f_9(yold))/DeltaY
        return DP
    

In [8]:
# 1.f (10 puntos)
# Usando la función de derivadas, implemente F como sugiere el libro
# y calcule el Jacobiano como la inversa de F.

F = np.zeros([9,9])
for i in range(9):
    for j in range(9):
        F[i,j] = DerivadaParcial(i+1,j,y)

print("Matriz de derivadas parciales")
print(F)
print("")
print("Jacobiano")
Jacobiano = np.linalg.inv(F)
print(Jacobiano)


Matriz de derivadas parciales
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  4.00000000e+00
   4.00000000e+00  4.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 4.00000000e+00  4.00000000e+00 -4.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.00000000e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  9.99999999e-01  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+01
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -2.00000000e+01  0.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [ 2.00000100e+00  0.00000000e+00  0.00000000e+00  1.00008890e-0

In [9]:
# 1.g (10 puntos)

DeltaYg = np.dot(-Jacobiano,vec)

print ( "DeltaY \n")
print(DeltaYg)
print(" ")
print("No cambia porque empezamos con la solución al problema")

DeltaY 

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 
No cambia porque empezamos con la solución al problema


In [10]:
#1.h (10 puntos)
# Calcule y_new a partir de y y delta y
y = y + DeltaYg 

In [11]:
y

array([ 1.,  0.,  1.,  0.,  1.,  0., 10.,  0., 20.])

In [12]:
#1.i (10 puntos)
# Compare f(y) con f(y_new). ¿Mejoró, empeoró o se quedó igual?
print(f_vec(y))
print("No cambió el vector de solución debido a que los valores quderaon intactos al calcular el cambio o paso de y")

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
No cambió el vector de solución debido a que los valores quderaon intactos al calcular el cambio o paso de y


In [13]:
# 1.j (50 puntos si todo funciona bien) 
# Escriba una función que realice varias iteraciones
# delta y = - Jacobiano * f(y)
# y_new = y + delta y
# y = y_new
# y se detenga cuando el valor absoluto de todos 
# los nueve elementos de f(y) sean menores que epsilon
# Imprima el número de pasos realizados

def NR_Multidimensional(yind):
    
    error = 1*10**(-6)
    # Parámetro para medir si todos los valores del vector cumplen con el error esperado
    a = 0
    
    while a == 0:
        
        F = np.zeros([9,9])
        for i in range(9):
            for j in range(9):
                F[i,j] = DerivadaParcial(i+1,j,yind)
    
        Vec = f_vec(yind)
            
        Jacobiano = np.linalg.inv(F)
        DeltaYg = np.dot(Jacobiano,Vec)
    
        yind = yind + DeltaYg
        Vec = f_vec(yind)
        
        # Verificar que todos los valores del vector sean menores a epsilon
        a = 1
        for i in range(len(Vec)):
            if Vec[i]<error and Vec[i]> (-error):
                a = a*1
            else:
                a = a*0
        
    return yind, Vec

In [14]:
# Haga el experimento casero para calcular la solución 
# con las condiciones propuestas en el libro
# Condiciones de prueba: masas colgando CON tensión T2
L, L1, L2, L3  = 8, 3, 4, 4  # Longitudes
W1, W2         = 10, 20      # Pesos

In [15]:
# Condiciones iniciales del problema
x1 = np.sin(np.pi/4)
x2 = np.sin(np.pi/6)
x3 = np.sin(np.pi/3)
x4 = np.cos(np.pi/4)
x5 = np.cos(np.pi/4)
x6 = np.cos(np.pi/4)
x7 = 10
x8 = 12
x9 = 15

# Vector y para la primera iteración
y2 = [x1,x2,x3,x4,x5,x6,x7,x8,x9]
print(y2)

[0.7071067811865475, 0.49999999999999994, 0.8660254037844386, 0.7071067811865476, 0.7071067811865476, 0.7071067811865476, 10, 12, 15]


In [16]:
# Ahora Buscamos la solución usando el método de Newton-Rhapson Multidimensional
NR_Multidimensional(y2)

LinAlgError: Singular matrix